import './globals.css'
import '../styles/main.scss';

import { Rootlayout } from './types/rootlayout'
import Header from './header/header'
import Navigation from "./header/navigation";



export const metadata = {
  title: 'Onlineshop with NextJS',
  description: 'Generated by Bjoern Zschernack and create next app',
}

export default function RootLayout({ children }: Rootlayout) {
  return (
    <html lang="en">
      <body>
     
        <main>
          <Header />

         {children}
        </main>
      </body>
    </html>
  )
}
