import './globals.css'
import { Rootlayout } from './types/rootlayout'
import 'bootstrap/dist/css/bootstrap.css'


export const metadata = {
  title: 'Onlineshop with NextJS',
  description: 'Generated by Bjoern Zschernack and create next app',
}

export default function RootLayout({ children }: Rootlayout) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
